Parker dev
flywheel-apps/mriqc pull request #33
Opened 2020-02-25 17:24 UTC by dpark6060

Added option to manifest to include rating widget (off by default).  If "include rating widget" is false, a python script is run to remove the html code.  This will need to be updated as fmriprep changes their output html file

2020-02-25 21:05 UTC, NPann approved these changes
Looking all good to me!

2020-02-26 20:05 UTC, lmperry requested changes
Looks good!  Small change request for version bump.

2020-02-26 20:05 UTC, lmperry commented on manifest.json
> +  "version": "0.6.5_0.15.1_dev5",
I would bump this to 0.7.0 as we're adding a new feature (config option) with default settings that will result in a different output file than the previous version.

2020-03-06 21:21 UTC, lmperry approved these changes

2020-03-06 21:26 UTC, merged