V0.2
flywheel-apps/mriqc pull request #4
Opened 2017-05-05 21:29 UTC by jenreiter

Fixes #2 

Note on this new functionality: If the input filename is in BIDS format, the run script will not look at the config file for the file “measurement” but will trust the BIDS format is correctly indicating Functional or Structural. If the filename is NOT in BIDS format, then the config file is read in and the “measurement” value is read in. The default value is “Functional”.

Also, I was not sure what term to use to describe the input T1w/T2w image. I was deciding between “Structural” and “Anatomical”. I have chosen “Structural” but wanted to know your preference.

Testing was executed on the dev platform for Functional and Structural T1w images. Files were in BIDS format as well as not in BIDS format. The MRIQC gear allows for T1w or T2w images. T2w images were not used in testing. Datasets can be found on the dev site:

Project: Project Name
Subject: Test
Acquisition: MRIQC Gear Test

2017-05-09 16:58 UTC, ryansanford commented
@lmperry Can you review these changes? Need anything from me/Thad?

2017-05-10 14:09 UTC, lmperry commented
@jenreiter: Looking at the [MRIQC release notes](https://github.com/poldracklab/mriqc/releases), it appears that support for T2 workflows was sorted out in a release after the one that is rolled into this gear (which is a few months old). Let's get the latest release (0.9.3) incorporated in this Gear and test to make sure it appropriately handles T2w images.

2017-05-24 05:12 UTC, lmperry requested changes
Looking at the MRIQC release notes, it appears that support for T2 workflows was sorted out in a release after the one that is rolled into this gear (which is a few months old). Let's get the latest release (0.9.3) incorporated in this Gear and test to make sure it appropriately handles T2w images as well.

2017-06-08 22:09 UTC, lmperry approved these changes

2017-06-08 22:09 UTC, merged